org: bogdan24
app: aws-node-project
service: aws-study

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    MAIL_QUEUE_URL: ${self:custom.MailQueue.url}
    AUCTIONS_BUCKET_NAME: ${self:custom.AuctionsBucket.name}
  iamRoleStatements:
    - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}
    - ${file(iam/MailQueueIAM.yml):MailQueueIAM}
    - ${file(iam/AuctionsBucketIAM.yml):AuctionsBucketIAM}

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}
    AuctionsBucket: ${file(resources/AuctionsBucket.yml):AuctionsBucket}
    AuctionsBucketPolicy: ${file(resources/AuctionsBucket.yml):AuctionsBucketPolicy}

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          path: auction
          method: post
          cors: true
          authorizer:
            arn:aws:lambda:us-east-1:215112191743:function:auth-service-dev-auth

  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - http:
          path: auctions
          method: get
          cors: true
          authorizer:
            arn:aws:lambda:us-east-1:215112191743:function:auth-service-dev-auth
  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - http:
          path: auction/{id}
          method: get
          cors: true
          authorizer:
            arn:aws:lambda:us-east-1:215112191743:function:auth-service-dev-auth
  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - http:
          path: auction/{id}/bid
          method: patch
          cors: true
          authorizer:
            arn:aws:lambda:us-east-1:215112191743:function:auth-service-dev-auth

  processAuctions:
    handler: src/handlers/processAuctions.handler
#    events:
#      - schedule: rate(1 minute)

  uploadAuctionPicture:
    handler: src/handlers/uploadAuctionPicture.handler
    events:
      - http:
          method: PATCH
          path: auction/{id}/picture
          cors: true
          authorizer:
            arn:aws:lambda:us-east-1:215112191743:function:auth-service-dev-auth

custom:
  MailQueue:
    arn: arn:aws:sqs:us-east-1:215112191743:MailQueue-dev
    url: https://sqs.us-east-1.amazonaws.com/215112191743/MailQueue-dev
  AuctionsBucket:
    name: auctions-bucket-bogdan-lubinskyj-dev