org: bogdan24
app: aws-node-project
service: aws-study

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          path: auction
          method: post
          cors: true

  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - http:
          path: auctions
          method: get
          cors: true

  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - http:
          path: auction/{id}
          method: get
          cors: true
