org: bogdan24
app: aws-node-project
service: aws-study

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          path: auction
          method: post
          cors: true
          authorizer:
            arn:aws:lambda:us-east-1:215112191743:function:auth-service-dev-auth
  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - http:
          path: auctions
          method: get
          cors: true
          authorizer:
            arn:aws:lambda:us-east-1:215112191743:function:auth-service-dev-auth
  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - http:
          path: auction/{id}
          method: get
          cors: true
          authorizer:
            arn:aws:lambda:us-east-1:215112191743:function:auth-service-dev-auth
  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - http:
          path: auction/{id}/bid
          method: patch
          cors: true
          authorizer:
            arn:aws:lambda:us-east-1:215112191743:function:auth-service-dev-auth

  processAuctions:
    handler: src/handlers/processAuctions.handler
#    events:
#      - schedule: rate(1 minute)