org: bogdan24
app: aws-node-project
service: aws-study

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}

functions:
  createAuction:
    handler: src/handlers/createAuction.createAuction
    events:
      - http:
          path: auction
          method: post
          cors: true
